### ISSUE TITLE
跑 python exps/dair-v2x/bev_height_lss_r50_864_1536_128x128.py --amp_backend native -b 8 --gpus 8 遇到报错

### ISSUE THREAD

**Issue by LetStarFly** [ADLab-AutoDrive/BEVHeight#16]
Traceback (most recent call last):
  File "exps/dair-v2x/bev_height_lss_r50_864_1536_128x128.py", line 18, in <module>
    from models.bev_height import BEVHeight
  File "/data/workspace/BEVHeight/models/bev_height.py", line 3, in <module>
    from layers.backbones.lss_fpn import LSSFPN
  File "/data/workspace/BEVHeight/layers/backbones/__init__.py", line 1, in <module>
    from .lss_fpn import LSSFPN
  File "/data/workspace/BEVHeight/layers/backbones/lss_fpn.py", line 12, in <module>
    from ops.voxel_pooling import voxel_pooling
  File "/data/workspace/BEVHeight/ops/voxel_pooling/__init__.py", line 1, in <module>
    from .voxel_pooling import voxel_pooling
  File "/data/workspace/BEVHeight/ops/voxel_pooling/voxel_pooling.py", line 5, in <module>
    from . import voxel_pooling_ext
ImportError: /data/workspace/BEVHeight/ops/voxel_pooling/voxel_pooling_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z37voxel_pooling_forward_kernel_launcheriiiiiiPKiPKfPfPiP11CUstream_st

**Comment by zhaoyanchen123** [comment]
需要将BEVHeight代码路径加入Python环境变量，可在terminal中输入 export PYTHONPATH=./$PYTHONPATH

**Comment by LetStarFly** [comment]
我以及按照您的回复进行了如上的修改，但问题还是没有解决。  

另外，nvidia-smi 什么都不显示，不知道别的同学配置这个环境的时候有没有相同的情况，  我想问一下这个正常吗 ？

**Comment by tdd233** [comment]
> export PYTHONPATH=./$PYTHONPATH

您好~请问您最后解决这个报错了嘛？
