### ISSUE TITLE
single-infrastructure-split-data.json is missing,please tell me how to get the file?

### ISSUE THREAD

**Issue by Egozjuer** [ADLab-AutoDrive/BEVHeight#2]
Traceback (most recent call last):
  File "scripts/data_converter/dair2kitti.py", line 89, in <module>
    gen_ImageSet_from_split_data(ImageSets_path, split_json_path, "infrastructure")
  File "/data/fq/perception/od/BEVHeight/scripts/data_converter/gen_kitti/gen_ImageSets_from_split_data.py", line 6, in gen_ImageSet_from_split_data
    split_data = read_json(split_data_path)
  File "/data/fq/perception/od/BEVHeight/scripts/data_converter/gen_kitti/utils.py", line 19, in read_json
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/single-infrastructure-split-data.json'

**Comment by yanglei18** [comment]
Thanks for your attention, we have uploaded 'data/single-infrastructure-split-data.json' in the code base.

**Comment by Egozjuer** [comment]
> Thanks for your attention, we have uploaded 'data/single-infrastructure-split-data.json' in the code base.
hello,I encountered another question
__init__() missing 1 required positional argument: 'bda_aug_conf'
  File "/data/fq/perception/od/BEVHeight/exps/dair-v2x/bev_height_lss_r50_864_1536_128x128.py", line 316, in train_dataloader
    return_depth=False,
  File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1501, in call_hook
    output = model_fx(*args, **kwargs)
  File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 296, in dataloader
    return self.instance.trainer.call_hook(self.name, pl_module=self.instance)
  File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 611, in request_dataloader
    dataloader = source.dataloader()
  File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 365, in reset_train_dataloader
    self.train_dataloader = self.request_dataloader(RunningStage.TRAINING, model=model)
  File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 595, in reset_train_val_dataloaders

**Comment by Egozjuer** [comment]
> Thanks for your attention, we have uploaded 'data/single-infrastructure-split-data.json' in the code base.
@yanglei18 
Thanks for your attention, we have uploaded 'data/single-infrastructure-split-data.json' in the code base.
hello,I encountered another question
init() missing 1 required positional argument: 'bda_aug_conf'
File "/data/fq/perception/od/BEVHeight/exps/dair-v2x/bev_height_lss_r50_864_1536_128x128.py", line 316, in train_dataloader
return_depth=False,
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1501, in call_hook
output = model_fx(*args, **kwargs)
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 296, in dataloader
return self.instance.trainer.call_hook(self.name, pl_module=self.instance)
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 611, in request_dataloader
dataloader = source.dataloader()
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 365, in reset_train_dataloader
self.train_dataloader = self.request_dataloader(RunningStage.TRAINING, model=model)
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 595, in reset_train_val_dataloaders

**Comment by Egozjuer** [comment]
> Thanks for your attention, we have uploaded 'data/single-infrastructure-split-data.json' in the code base.
@yanglei18 
hello,I encountered another question
init() missing 1 required positional argument: 'bda_aug_conf'
File "/data/fq/perception/od/BEVHeight/exps/dair-v2x/bev_height_lss_r50_864_1536_128x128.py", line 316, in train_dataloader
return_depth=False,
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1501, in call_hook
output = model_fx(*args, **kwargs)
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 296, in dataloader
return self.instance.trainer.call_hook(self.name, pl_module=self.instance)
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 611, in request_dataloader
dataloader = source.dataloader()
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 365, in reset_train_dataloader
self.train_dataloader = self.request_dataloader(RunningStage.TRAINING, model=model)
File "/root/miniconda3/envs/mmlab/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 595, in reset_train_val_dataloaders
